### ISSUE TITLE
The nvcc packages do not honor `cuda-version`

### ISSUE THREAD

**Issue by leofang** [conda-forge/nvcc-feedstock#108]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

@pentschev reported offline that `nvcc_linux-64` 11.8 can coexist with a CUDA 12.x environment. It turns out that the recipe here does not make `cuda-version` a dependency:
```yaml
channels:
  - rapidsai-nightly
  - dask/label/dev
  - conda-forge
  - nvidia
dependencies:
# Base
  - python=3.10
  # - cudatoolkit=11.8
  - cuda-version=12.5
...
  - nvcc_linux-64=11.8
...
```

### Installed packages

n/a

### Environment info

n/a
